.test_browser: &test_browser
    stage: test
    before_script:
        - npm ci
    timeout: "15m"
    variables:
        npm_config_cache: &npm_cache_path "$CI_BUILDS_DIR/.node_cache_pegasus"
        CHROME_BIN: "chromium-browser"
        MAPBOX_API_KEY: "key-is-not-required"
        PRODUCTION: "false"
    script:
        - npm run test:ci
    coverage: '/All files \|\s*(\d+(\.\d+)?)/'

cache:
  key: "ilias_pegasus_node_cache"
  paths:
    - "$npm_config_cache"

stages:
  - lint
  - test

lint:
    stage: lint
    before_script:
        - npm ci
    timeout: "5m"
    variables:
        npm_config_cache: *npm_cache_path
    script:
        - npm run lint
    allow_failure: true
    image: node:lts-alpine

test:chrome_77:
    <<: *test_browser
    image: zenika/alpine-chrome:77-with-node

test:chrome_76:
    <<: *test_browser
    image: zenika/alpine-chrome:76-with-node

