.test_browser: &test_browser
    stage: test
    before_script:
        - npm ci
    timeout: "15m"
    variables:
        npm_config_cache: "$CI_BUILDS_DIR/.node_cache_pegasus"
        CHROME_BIN: "chromium-browser"
    script:
        - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI

cache:
  key: "ilias_pegasus_node_cache"
  paths:
    - "$npm_config_cache"

stages:
  - test

test:chrome_77:
    <<: *test_browser
    image: zenika/alpine-chrome:77-with-node

test:chrome_76:
    <<: *test_browser
    image: zenika/alpine-chrome:76-with-node

test:chrome_75:
    <<: *test_browser
    image: zenika/alpine-chrome:75-with-node
